### ISSUE TITLE
Support arch linux

### ISSUE THREAD

**Issue by maksimr** [mivoligo/Zeegaree#3]
What about support arch linux?
When I work on Ubuntu it was very helpful application. Now I miss him on arch linux.

**Comment by mivoligo** [comment]
Unfortunately I have no experience with Arch. If there's anyone who can make it work, please let me know.

**Comment by maksimr** [comment]
@mivoligo I think I made it work... but I remove Unity from zeegaree.py
add parenthetical for `print` and install

``` sh
yaourt -S python-pyside
yaourt -S python-dbus
```

and now run `python zeegaree.py` launch Zeegaree.

thx

**Comment by mivoligo** [comment]
Awesome! Feel free to add instructions how to do that to README. :+1:

**Comment by mivoligo** [comment]
Thanks for your help, much appreciated!
