### ISSUE TITLE
No module named gi.repository

### ISSUE THREAD

**Issue by ghost** [mivoligo/Zeegaree#6]
I had this error 

> Traceback (most recent call last):
>   File "zeegaree.py", line 4, in <module>
>     from gi.repository import Notify
> ImportError: No module named gi.repository

Which I fixed on my ubuntu 16.04 system by doing the following

sudo apt install python-gobject
sudo apt install python-dbus

Was not sure where to put this solution as im new to Git

**Comment by writepavel** [comment]
I had the same error in ubuntu 16.04 and my fix was:

sudo apt-get install --reinstall python-gi
sudo apt-get install python3-pyside

Possible difference due to differences in python versions.

**Comment by aamnah** [comment]
i extracted the files and installed the packages mentioned in the readme and ran the python file.. was getting the same `No module named gi.repository`. i first did this:

```
sudo apt-get install --reinstall python-gi
sudo apt-get install python3-pyside
```
which gave me 

```
Downloads/Zeegaree-master/zeegaree.py:4: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
Traceback (most recent call last):
  File "Downloads/Zeegaree-master/zeegaree.py", line 9, in <module>
    import dbus.service
ImportError: No module named dbus.service
```

then i did:

```
sudo apt install python-dbus
```

and tried again and it worked, but it kept giving me 

```
file:///home/aamnah/Downloads/Zeegaree-master/Calendar.qml:286: TypeError: Result of expression 'doneWorkArray' [undefined] is not an object.
```

so i did

```
sudo apt install python-gobject
```

works fine now.

**Comment by vzickus** [comment]
Same issue. None of the above solutions worked.

**Comment by usmajor** [comment]
check in your pakages folder
/usr/local/lib/python3.6/dist-packages  or 3.5 or 3.4 
and also in 
/usr/local/lib/python3/dist-packages
you should have a folder **gi** in both of them .. 
remove or rename **/usr/local/lib/python3.6/dist-packages/gi**

**Comment by gitjonez** [comment]
Sort of takes up ridiculous amount of CPU. You can see at the 30s mark where I closed up-clock.
![up-clock-cpu](https://user-images.githubusercontent.com/14845953/32764587-48ed115a-c8bb-11e7-974f-9be992118291.png)

**Comment by kuchaguangjie** [comment]
In my case, it's because I have installed python3 via `brew`, after uninstall it via:

 `brew remove python3   brew uninstall --ignore-dependencies python3`

Then re-open another terminal to take effect, then the issue is fixed.
